CREATE DEFINER=`root`@`localhost` FUNCTION `DURACION`(V_IDPLACA VARCHAR(30)) RETURNS int(11)
    DETERMINISTIC
BEGIN
    DECLARE FECIN TIMESTAMP;
    SET FECIN = (
        SELECT FecIngre FROM ticket
        WHERE IDPLACA = V_IDPLACA
        ORDER BY FecIngre DESC LIMIT 1
    );
    RETURN TIMESTAMPDIFF(MINUTE, FECIN, NOW());
END