CREATE DEFINER=`root`@`localhost` PROCEDURE `REGISTRAR_SALIDA`(IN V_IDPLACA VARCHAR(30))
BEGIN
    DECLARE V_IdTick INT;
    DECLARE V_DURACION INT;
    DECLARE V_VALOR INT;
    DECLARE V_TARIFA INT;

    SELECT IdTick INTO V_IdTick FROM ticket
    WHERE IDPLACA = V_IDPLACA
    ORDER BY FecIngre DESC LIMIT 1;

    SET V_DURACION = DURACION(V_IDPLACA);

    SELECT TARI INTO V_TARIFA FROM zonparq LIMIT 1;

    SET V_VALOR = V_DURACION * V_TARIFA;

    UPDATE factura
    SET duracion = V_DURACION,
        ValPag = V_VALOR,
        FecEgre = NOW()
    WHERE IdTick = V_IdTick;
END